In [1]:
# Dokumen-dokumen
dokumen1 = "saya sangat suka belajar matematika"
dokumen2 = "matematika adalah ilmu yang menarik"
dokumen3 = "saya suka ilmu pengetahuan matematika"

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

# List dokumen
dokumen_list = [dokumen1, dokumen2, dokumen3]

# Inisialisasi TfidfVectorizer
vectorizer = TfidfVectorizer()

# Menghitung TF-IDF
tfidf_matrix = vectorizer.fit_transform(dokumen_list)

# Mendapatkan daftar kata (fitur) dan TF-IDF matriks
df_tfidf = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())

# Menampilkan hasil dalam DataFrame
df_tfidf = df_tfidf.transpose()  # Transpose agar tampil sesuai dengan tabel di gambar
df_tfidf.columns = ['Dokumen 1', 'Dokumen 2', 'Dokumen 3']  # Memberi nama kolom
df_tfidf.index.name = 'Kata'  # Memberi nama index

# Menampilkan hasil TF-IDF dalam format tabel
print(df_tfidf)

             Dokumen 1  Dokumen 2  Dokumen 3
Kata                                        
adalah        0.000000   0.504611   0.000000
belajar       0.534093   0.000000   0.000000
ilmu          0.000000   0.383770   0.433067
matematika    0.315444   0.298032   0.336315
menarik       0.000000   0.504611   0.000000
pengetahuan   0.000000   0.000000   0.569431
sangat        0.534093   0.000000   0.000000
saya          0.406192   0.000000   0.433067
suka          0.406192   0.000000   0.433067
yang          0.000000   0.504611   0.000000


In [3]:
import numpy as np
from scipy.linalg import svd

# Melakukan SVD
U, S, VT = svd(tfidf_matrix.toarray())

# Menampilkan hasil SVD
print("\nMatriks U:")
print(U)
print("\nNilai Singular:")
print(S)
print("\nMatriks V^T:")
print(VT)


Matriks U:
[[-0.60814552  0.48862709 -0.62562176]
 [-0.41400019 -0.86766853 -0.27523657]
 [-0.67732036  0.09162364  0.72996044]]

Nilai Singular:
[1.25458761 0.95860451 0.71210063]

Matriks V^T:
[[-0.16651622 -0.25889503 -0.3604418  -0.43282278 -0.16651622 -0.30742143
  -0.25889503 -0.43069826 -0.43069826 -0.16651622]
 [-0.45674246  0.27224209 -0.30597178 -0.07682382 -0.45674246  0.05442633
   0.27224209  0.24843975  0.24843975 -0.45674246]
 [-0.19503914 -0.46923205  0.29559607 -0.04757929 -0.19503914  0.58371244
  -0.46923205  0.08706529  0.08706529 -0.19503914]
 [-0.34421626 -0.0986162  -0.2026577   0.86083088 -0.00503896 -0.08754232
  -0.14305252 -0.17537332 -0.17537332 -0.00503896]
 [-0.46717666  0.28611077  0.0528597  -0.16417888  0.76197109  0.10297975
  -0.14292985 -0.03038308 -0.03038308 -0.23802891]
 [ 0.21464752  0.0235798  -0.63538984 -0.01227279  0.13791567  0.67405742
   0.16724727 -0.12069187 -0.12069187  0.13791567]
 [-0.33027964 -0.47666231  0.23940083 -0.05918214  0.0